### ISSUE TITLE
Trouble starting the simulator

### ISSUE THREAD

**Issue by denzilsaldanha** [coyotegalileo/aocalhas#1]
I downloaded the master version of the code, i'm having trouble trying to make it run.
Is it possible to give me a small insight on how the code works.

**Comment by Cartucho** [comment]
@coyotegalileo

**Comment by coyotegalileo** [comment]
I have updated the readme file. Hopefully it will help. I haven't run this for a long time, so I am not sure if I missed anything.

**Comment by denzilsaldanha** [comment]
I followed the instructions. Still getting an error

I run a command like this 
g++ -std=c++11 -g -Iinclude ../auto_pilot/auto_pilot.cpp ../airplane/airplane.cpp ../checksum/checksum.cpp ../converts/converts.cpp ../auto_pilot/determine_velocity.cpp -o autop

And i get the following error 

g++: error: ../auto_pilot/auto_pilot.cpp: No such file or directory
g++: error: ../airplane/airplane.cpp: No such file or directory
g++: error: ../checksum/checksum.cpp: No such file or directory
g++: error: ../converts/converts.cpp: No such file or directory
g++: error: ../auto_pilot/determine_velocity.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.

**Comment by coyotegalileo** [comment]
The folder names changed slightly, since I last used them. I think the new commit solved the compilation!

**Comment by denzilsaldanha** [comment]
Sorry for the trouble, but I downloaded the latest commit and tried running the commands and am still getting the same errors. 


g++: error: ../Auto_pilot/auto_pilot.cpp: No such file or directory
g++: error: ../Airplane/airplane.cpp: No such file or directory
g++: error: ../Checksum/checksum.cpp: No such file or directory
g++: error: ../Converts/converts.cpp: No such file or directory
g++: error: ../Auto_pilot/determine_velocity.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.

**Comment by denzilsaldanha** [comment]
The ./mux and ./preout files need to be compiled. Could you kindly share the code for that?

**Comment by coyotegalileo** [comment]
Sorry I could not solve this earlier, but right now if you follow the instructions in the readme file you will be able to run the program. Bare in mind that this is very unfinished work so the code is not clean and the results you see may be confusing for you.
